---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []

---
# DevX engineering productivity group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: devx
  description: Developer Experience (DevX) core group
spec:
  type: team
  profile:
    displayName: DevX Team
  children: []

---
# Primary user linked to GitHub login 'jaimehenao8126'
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jaimehenao8126
  description: Jaime Henao
spec:
  profile:
    displayName: Jaime Henao
    email: jaime.henao@example.com
  memberOf:
    - devx
