apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Portfolio-jaime/Backstage-Manual.git'
    targetRevision: main
    path: Manifest
  destination:
    server: 'https://kubernetes.default.svc'
  namespace: backstage-manual
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
