apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backstage-ingress
  namespace: backstage-manual
  annotations:
    # Solo la anotación de tracking, sin rewrite-target
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true" # habilitar cuando tengas TLS
spec:
  rules:
    - host: backstage.local
      http:
        paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: backstage
                  port:
                    number: 80
  # tls:
  #   - hosts:
  #       - backstage.local
  #     secretName: backstage-tls
