apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage-manual
type: Opaque
data:
  GITHUB_TOKEN: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKaGNtZHZZMlFpTENKemRXSWlPaUpoWkcxcGJqcGhjR2xMWlhraUxDSnVZbVlpT2pFM05qRXhOek0zTXpnc0ltbGhkQ0k2TVRjMk1URTNNemN6T0N3aWFuUnBJam9pTVdZd1lXSm1OekV0T0dZMU55MDBPVGN5TFRnMk9HTXROMlE1WVRneVkyWmhPVEExSW4wLlFSVE1xTm5yN3ROWkwxalFXRTU3LXpfNncwams1VVdqTGNtQlRGY1lJN2M=
  BACKEND_AUTH_SECRET: c2VjcmV0X2tleV9iYWNrU3RhZ2U=
  BACKEND_AUTH_KEYS_0_SECRET: c2VjcmV0X2tleV9iYWNrU3RhZ2U=