apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: backstage
type: Opaque
data:
  POSTGRES_USER: amFpbWU=
  POSTGRES_PASSWORD: amFpbWU=
  POSTGRES_DB: YmFja3N0YWdl
  POSTGRES_PORT: NTQzMg==